workflows:
  android-build:
    name: Coin Galaxy Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: latest
      java: 17
      groups:
        - google_play_credentials # If you have signing keys
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build Web App
        script: npm run build
      - name: Capacitor Sync
        script: |
          npx cap sync android
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk